
//Product types
export const GET_PRODUCTS='GET_PRODUCTS';
export const ADD_PRODUCT='ADD_PRODUCT';
export const DELETE_PRODUCT='DELETE_PRODUCT';
export const PRODUCTS_LOADING='PRODUCTS_LOADING';
export const ADD_TO_CART='ADD_TO_CART';
export const GET_PRODUCT_BY_ID='GET_PRODUCT_BY_ID'
export const EDIT_PRODUCT='EDIT_PRODUCT'



//Cart types
export const GET_CART='GET_CART';
export const REMOVE_FROM_CART='REMOVE_FROM_CART';
export const CART_LOADING='PRODUCTS_LOADING';
export const EDIT_CART='EDIT_CART'

//Auth
export const USER_LOADING='USER_LOADING';
export const USER_LOADED='USER_LOADED';
export const AUTH_ERROR='AUTH_ERROR';
export const LOGIN_SUCCESS='LOGIN_SUCCESS';
export const LOGIN_FAIL='LOGIN_FAIL';
export const LOGOUT_SUCCESS='LOGOUT_SUCCESS';
export const REGISTER_SUCCESS='REGISTER_SUCCESS';
export const REGISTER_FAIL='REGISTER_FAIL';
export const GET_ERRORS='GET_ERRORS';
export const CLEAR_ERRORS='CLEAR_ERRORS';
//ALERT
export const SET_ALET='SET_ALERT'
export const REMOVE_ALERT='REMOVE_ALERT'
